version: "3"

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - webhooks-network

  master:
    build: .
    environment:
      - SERVER_SLAVE_HOST=slave:5001
      - SERVER_MASTER_HOST=master:5000
      - SERVER_PORT=5000
    volumes:
      - ./:/app
      - ~/go:/go
      - ./../:/go/src/gitlab.com/oivoodoo/
    command: "go run /go/src/gitlab.com/oivodoo/server/cmd/master/main.go"
    ports:
      - "5000:5000"
    links:
      - "dynamodb:dynamodb"
    depends_on:
      - dynamodb
    networks:
      - webhooks-network

  slave:
    build: .
    volumes:
      - ./:/app
      - ~/go:/go
      - ./../:/go/src/gitlab.com/oivoodoo/
    command: "go run /go/src/gitlab.com/oivodoo/server/cmd/slave/main.go"
    environment:
      - SERVER_SLAVE_HOST=slave
      - SERVER_MASTER_HOST=master
      - SERVER_PORT=5001
    ports:
      - "5000:5001"
    links:
      - "dynamodb:dynamodb"
    depends_on:
      - dynamodb
    networks:
      - webhooks-network

networks:
  webhooks-network:
    external: true
